import Breadcrumb from '@/components/Panel/Breadcrumb/Breadcrumb'
import PanelLayout from '@/components/Panel/PanelLayout'
import Rooms from '@/components/Panel/Rooms/Rooms'
import Head from 'next/head'
import React from 'react'
import { FaBed } from 'react-icons/fa'

const Dashboard = () => {
  return (
    <> 
    <Head>
        <title>Uredjaji - HomeLab</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <PanelLayout>  
      <Breadcrumb/> 
      <Rooms/> 
    </PanelLayout>
    </>
  )
}

export default Dashboard