import Breadcrumb from '@/components/Panel/Breadcrumb/Breadcrumb'
import CurrentStats from '@/components/Panel/Home/CurrentStats'
import TemperatureGraph from '@/components/Panel/Home/TemperatureGraph'
import PanelLayout from '@/components/Panel/PanelLayout'
import Head from 'next/head'

const Dashboard = () => {
  return (
    <> 
    <Head>
        <title>Panel - HomeLab</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <PanelLayout>  
      <Breadcrumb/>
      <CurrentStats/>
      <TemperatureGraph/>
    </PanelLayout>
    </>
  )
}

export default Dashboard