import Hero from '@/components/Landing/Hero/Hero'
import Navbar from '@/components/Landing/Navbar/Navbar'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Hackaton</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar></Navbar>
        <Hero></Hero>
      </main>
    </>
  )
}
